name: Test for documents
on:
  push:
    branches:
      - main

jobs:
  docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - if: runner.os == 'ubuntu-latest'
        name: Maximize build space
        run: 'sudo rm -rf /usr/share/dotnet

          sudo rm -rf /opt/ghc

          sudo rm -rf "/usr/local/share/boost"

          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

          sudo rm -rf /usr/local/lib/android

          sudo docker image prune --all --force

          sudo rm -rf /opt/hostedtoolcache/CodeQL

          '
      - id: measurement-2
        name: Record Measurement After Maximize build space
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Maximize build space
          task: get-measurement
      - uses: actions/checkout@v4
      - name: Cache pip packages for Linux
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('**/**/docs/requirements.txt') }}
          path: ~/.cache/pip
          restore-keys: '${{ runner.os }}-pip-

            '
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (docs)
        run: pip install -r requirements.txt
        shell: bash -l {0}
        working-directory: ./docs
      - id: measurement-7
        name: Record Measurement After Install dependencies (docs)
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install dependencies (docs)
          task: get-measurement
      - name: Build docs
        run: make clean html
        shell: bash -l {0}
        working-directory: ./docs
      - id: measurement-9
        name: Record Measurement After Build docs
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build docs
          task: get-measurement
      - name: DocTest (Tutorials)
        run: make doctest_tutorials
        shell: bash -l {0}
        working-directory: ./docs
      - id: measurement-11
        name: Record Measurement After DocTest (Tutorials)
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: DocTest (Tutorials)
          task: get-measurement
      - name: DocTest (Examples)
        run: make doctest_examples
        shell: bash -l {0}
        working-directory: ./docs
      - id: measurement-13
        name: Record Measurement After DocTest (Examples)
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: DocTest (Examples)
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - '3.9'
          - '3.11'
