name: Code Formatting
on:
  push:
    branches:
      - main

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - if: runner.os == 'ubuntu-latest'
        name: Maximize build space
        run: 'sudo rm -rf /usr/share/dotnet

          sudo rm -rf /opt/ghc

          sudo rm -rf "/usr/local/share/boost"

          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

          sudo rm -rf /usr/local/lib/android

          sudo docker image prune --all --force

          sudo rm -rf /opt/hostedtoolcache/CodeQL

          '
      - id: measurement-2
        name: Record Measurement After Maximize build space
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Maximize build space
          task: get-measurement
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        name: Set commit range (push to the master branch, e.g. merge)
        run: echo "COMMIT_RANGE=${{ github.event.before }}.." >> $GITHUB_ENV
      - id: measurement-5
        name: Record Measurement After Set commit range (push to the master branch,
          e.g. merge)
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Set commit range (push to the master branch, e.g. merge)
          task: get-measurement
      - if: github.event_name == 'pull_request'
        name: Set commit range (pull request)
        run: 'git fetch origin master

          echo "COMMIT_RANGE=origin/master..." >> $GITHUB_ENV

          '
      - id: measurement-7
        name: Record Measurement After Set commit range (pull request)
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Set commit range (pull request)
          task: get-measurement
      - if: runner.os == 'Linux'
        name: Cache pip packages for Linux
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements/**') }}
          path: ~/.cache/pip
          restore-keys: '${{ runner.os }}-pip-

            '
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create env.yml
        run: 'python -m pip install --upgrade pip;

          pip install conda-merge;

          sudo apt-get update

          sudo apt-get install -y libopenblas-dev libatlas-base-dev libblas-dev liblapack-dev
          libhdf5-dev

          cd requirements

          conda-merge env_common.yml env_test.yml env_ubuntu.yml tensorflow/env_tensorflow.cpu.yml
          torch/env_torch.cpu.yml jax/env_jax.cpu.yml > env.yml

          cd ..

          cp requirements/env.yml env.yml

          '
        shell: bash
      - id: measurement-11
        name: Record Measurement After Create env.yml
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Create env.yml
          task: get-measurement
      - name: Install all dependencies using micromamba
        uses: mamba-org/setup-micromamba@main
        with:
          create-args: python=${{ matrix.python-version }}
          environment-file: env.yml
          environment-name: deepchem
      - id: install
        name: Install DeepChem
        run: pip install -e .
        shell: bash -l {0}
      - id: measurement-14
        name: Record Measurement After Install DeepChem
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Install DeepChem
          task: get-measurement
      - name: Show files modified
        run: 'CHANGED_FILES=`git diff --name-only $COMMIT_RANGE || true`

          echo "changed files are $CHANGED_FILES"

          '
      - id: measurement-16
        name: Record Measurement After Show files modified
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Show files modified
          task: get-measurement
      - id: yapf
        name: Yapf (version 0.32.0)
        run: "CHANGED_FILES=`git diff --name-only $COMMIT_RANGE | grep .py$ || true`\n\
          if [ -n \"$CHANGED_FILES\" ]; then\n  yapf -d $CHANGED_FILES\nfi\n"
        shell: bash -l {0}
      - id: measurement-18
        name: Record Measurement After Yapf (version 0.32.0)
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Yapf (version 0.32.0)
          task: get-measurement
      - if: ${{ (success() || failure()) && (steps.install.outcome == 'failure' ||
          steps.install.outcome == 'success') }}
        name: Flake8
        run: source scripts/flake8_for_ci.sh
        shell: bash -l {0}
      - id: measurement-20
        name: Record Measurement After Flake8
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Flake8
          task: get-measurement
      - if: ${{ (success() || failure()) && (steps.install.outcome == 'failure' ||
          steps.install.outcome == 'success') }}
        name: Mypy
        run: 'mypy -p deepchem

          '
        shell: bash -l {0}
      - id: measurement-22
        name: Record Measurement After Mypy
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Mypy
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
    strategy:
      matrix:
        python-version:
          - '3.10'
