name: Release
on:
  push:
    branches:
      - main

jobs:
  docker:
    needs:
      - pypi
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - if: runner.os == 'ubuntu-latest'
        name: Maximize build space
        run: 'sudo rm -rf /usr/share/dotnet

          sudo rm -rf /opt/ghc

          sudo rm -rf "/usr/local/share/boost"

          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

          sudo rm -rf /usr/local/lib/android

          sudo rm -rf /opt/hostedtoolcache/CodeQL

          '
      - id: measurement-2
        name: Record Measurement After Maximize build space
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Maximize build space
          task: get-measurement
      - uses: actions/checkout@v4
      - id: get_tag_version
        name: Get the tag version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - id: measurement-5
        name: Record Measurement After Get the tag version
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Get the tag version
          task: get-measurement
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
      - id: docker_build
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/tag
          push: true
          tags: deepchemio/deepchem:${{ steps.get_tag_version.outputs.VERSION }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - id: measurement-9
        name: Record Measurement After Image digest
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Image digest
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
  pypi:
    runs-on: ubuntu-latest
    steps:
      - name: Start Energy Measurement
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: start-measurement
      - if: runner.os == 'ubuntu-latest'
        name: Maximize build space
        run: 'sudo rm -rf /usr/share/dotnet

          sudo rm -rf /opt/ghc

          sudo rm -rf "/usr/local/share/boost"

          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

          sudo rm -rf /usr/local/lib/android

          sudo rm -rf /opt/hostedtoolcache/CodeQL

          '
      - id: measurement-2
        name: Record Measurement After Maximize build space
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Maximize build space
          task: get-measurement
      - uses: actions/checkout@v4
      - name: Cache pip modules for Linux
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-pip-${{ hashFiles('env.*.yml') }}
          path: ~/.cache/pip
          restore-keys: '${{ runner.os }}-pip-

            '
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Build DeepChem
        run: 'python -m pip install --upgrade pip

          pip install -e .

          '
      - id: measurement-7
        name: Record Measurement After Build DeepChem
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Build DeepChem
          task: get-measurement
      - name: Import checking
        run: python -c "import deepchem"
      - id: measurement-9
        name: Record Measurement After Import checking
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Import checking
          task: get-measurement
      - name: Prepare for publishing
        run: 'rm -rf ./build ./dist ./*egg-info

          pip install setuptools wheel twine

          '
      - id: measurement-11
        name: Record Measurement After Prepare for publishing
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Prepare for publishing
          task: get-measurement
      - env:
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          TWINE_USERNAME: __token__
        name: Publish (Stable)
        run: 'python setup.py sdist bdist_wheel --release

          twine upload dist/*

          '
      - id: measurement-13
        name: Record Measurement After Publish (Stable)
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          label: Publish (Stable)
          task: get-measurement
      - id: display-measurement
        name: Display Energy Results
        uses: green-coding-solutions/eco-ci-energy-estimation@v4
        with:
          json-output: true
          task: display-results
      - name: Save Total Energy Consumption Data
        run: echo '${{ steps.final-measurement.outputs.data-total-json }}' > total_energy_consumption-${{
          github.run_id }}.json
      - name: Upload Energy Consumption Artifact
        uses: actions/upload-artifact@v4
        with:
          name: total-energy-consumption
          path: total_energy_consumption-${{ github.run_id }}.json
    strategy:
      matrix:
        python-version:
          - '3.9'
